AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for TiftoPdfConverterSam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  TiffToPdfConverterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/TiffToPdfConverter/
      Handler: TiffToPdfConverter::TiffToPdfConverter.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
      - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        ProcessCsv:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /processcsv
            Method: put

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TiffToPdfConverterApi:
    Description: API Gateway endpoint URL for Prod stage for TIFF to PDF Converter function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/processcsv/"
  TiffToPdfConverterFunction:
    Description: TIFF to PDF Converter Lambda Function ARN
    Value: !GetAtt TiffToPdfConverterFunction.Arn
  TiffToPdfConverterFunctionIamRole:
    Description: Implicit IAM Role created for TIFF to PDF Converter function
    Value: !GetAtt TiffToPdfConverterFunctionRole.Arn
